import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import BannerGallery from '../components/banner-gallery/banner-gallery';
import Categories from '../components/categories';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {/* <BannerGallery /> */}
    <Categories />
  </div>
);

export default Home;
